Improving CONTRIBUTING.md #2276
matteobruni/tsparticles pull request #2333
Opened 2021-10-11 19:58 UTC by timscodebase

Happy Hacktoberfest!

2021-10-11 20:23 UTC, timscodebase commented
Not sure why the 1 test is failing. Has to do with firebase

2021-10-11 20:57 UTC, matteobruni requested changes
It's generally good, but some changes are still required

2021-10-11 20:57 UTC, matteobruni commented on CONTRIBUTING.md
> +After that, you can start coding. The source folders are `core,` `wrappers,` and `plugins.`
The punctuation shouldn't go inside the \` quotes, also the folders are really different now, only `plugins` still exists. Can you update it?

2021-10-11 20:57 UTC, matteobruni commented on CONTRIBUTING.md
> +Once done editing, you can check if everything builds running `lerna run build.`
Punctuation should be kept outside of \` quotes

2021-10-11 20:57 UTC, matteobruni commented on CONTRIBUTING.md
> +yarn serve
Missing code quotes here

2021-10-11 20:57 UTC, matteobruni commented on CONTRIBUTING.md
> +The `wrappers` and `plugins` don't have a demo app inside the repository for now.
The `wrappers` folder doesn't exist anymore, now it's `components`

2021-10-11 20:57 UTC, matteobruni commented on CONTRIBUTING.md
> +A demo folder will probably be created in the near future with all the demo apps needed.
The `demo` folder exists now

2021-10-11 20:58 UTC, timscodebase commented on CONTRIBUTING.md
> +After that, you can start coding. The source folders are `core,` `wrappers,` and `plugins.`
yup

2021-10-11 21:27 UTC, matteobruni requested changes
Sorry, I forgot to give more details in the previous review

2021-10-11 21:27 UTC, matteobruni commented on CONTRIBUTING.md
> +After that, you can start coding. The source folders are `components` and `plugins`.
- `components` is where all third parties components are (React, Vue, etc.)
- `demo` where all the demos apps are
- `editor` is the source of the GUI editor
- `engine` is the main source folder
- `interactions` contains some additional interaction plugins
- `paths` contains some additional path plugins
- `plugins` contains some additional plugins (for now just `infection`, but more will come)
- `presets` contains some options presets with their bundle, ready to be used
- `shapes` contains some additional shape plugins
- `updaters` contains some additional updater plugins
- `website` contains the [website](https://particles.js.org) source

2021-10-11 21:27 UTC, matteobruni commented on CONTRIBUTING.md
> -The `core` folder contains tsParticles library, the main library.
`core` is now `engine`

2021-10-11 21:27 UTC, matteobruni commented on CONTRIBUTING.md
> +The `components` and `plugins` don't have a demo app inside the repository for now.
I forgot in the previous review, all plugins, components and engines have a demo app or page

2021-10-11 21:53 UTC, timscodebase commented
I will commit these changes by 6pm today PST

On Mon, Oct 11, 2021 at 2:27 PM Matteo Bruni ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Sorry, I forgot to give more details in the previous review
> ------------------------------
>
> In CONTRIBUTING.md
> <https://github.com/matteobruni/tsparticles/pull/2333#discussion_r726576997>
> :
>
> >
> -After that you can start coding, the source folders are `core`, `wrappers` and `plugins`.
> +After that, you can start coding. The source folders are `components` and `plugins`.
>
>
>    - components is where all third parties components are (React, Vue,
>    etc.)
>    - demo where all the demos apps are
>    - editor is the source of the GUI editor
>    - engine is the main source folder
>    - interactions contains some additional interaction plugins
>    - paths contains some additional path plugins
>    - plugins contains some additional plugins (for now just infection,
>    but more will come)
>    - presets contains some options presets with their bundle, ready to be
>    used
>    - shapes contains some additional shape plugins
>    - updaters contains some additional updater plugins
>    - website contains the website <https://particles.js.org> source
>
> ------------------------------
>
> In CONTRIBUTING.md
> <https://github.com/matteobruni/tsparticles/pull/2333#discussion_r726577097>
> :
>
> >
> -The `core` folder contains tsParticles library, the main library.
>
> core is now engine
> ------------------------------
>
> In CONTRIBUTING.md
> <https://github.com/matteobruni/tsparticles/pull/2333#discussion_r726577517>
> :
>
> >
> -The `wrappers` and `plugins` doesn't have a demo app inside the repository for now.
> +The `components` and `plugins` don't have a demo app inside the repository for now.
>
> I forgot in the previous review, all plugins, components and engines have
> a demo app or page
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/matteobruni/tsparticles/pull/2333#pullrequestreview-776673941>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQVCD7LQ4TLHV2UPZCDYCMLUGNJE5ANCNFSM5FY6TVMA>
> .
>

2021-10-11 23:17 UTC, timscodebase commented on CONTRIBUTING.md
> +After that, you can start coding. The source folders are `components` and `plugins`.
I added the list

2021-10-12 21:14 UTC, timscodebase commented
Any more changes needed @matteobruni?

2021-10-12 21:18 UTC, matteobruni commented
> Any more changes needed @matteobruni?

Sorry I was busy and didn’t notice the updates. Everything looks good to me. Thank you very much

2021-10-12 21:18 UTC, merged