#1228  - Sync Documentation
matteobruni/tsparticles pull request #2406
Opened 2021-10-26 21:38 UTC by lianplass

Documentation for Sync property alongside comments.  Unsure if path in comment is correct, but happy to correct if otherwise.

2021-10-26 22:04 UTC, matteobruni requested changes
Good job but I cannot merge it because it's not following the standard of other files.

You can see here the `IAnimatableColor` interface: https://github.com/matteobruni/tsparticles/blob/69156ca7abe5684d4353c2d1a60f5a789a7e881a/engine/src/Options/Interfaces/IAnimatableColor.ts#L7

It has a markdown file describing the interface instead of a single property. This is the standard followed everywhere.

So the `sync` property should be described everywhere where used, with all other interface/class properties.

2021-10-28 04:36 UTC, lianplass commented
Took another stab at it (hope I got it right this time!).  Once confirmed, i'll proceed with the others!

2021-10-28 07:02 UTC, matteobruni requested changes
Good job, everything's better now, some files still needs a review.

2021-10-28 07:02 UTC, matteobruni commented on engine/src/Options/Classes/AnimationOptions.ts
> + * [[include:engine\markdown\Sync.md]]
This line needs to be changed

2021-10-28 07:02 UTC, matteobruni commented on engine/src/Options/Classes/Particles/Life/Life.ts
> + * [[include:engine\markdown\Sync.md]]
This line needs to be changed

2021-10-29 06:19 UTC, matteobruni approved these changes
Everything looks good. Good job!

2021-10-29 06:53 UTC, merged